import Link from "next/link";
import Image from "next/image";

export default function PrivacyPage() {
  return (
    <div className="min-h-screen" style={{ background: "#f4f8fb" }}>
      {/* Header */}
      <div style={{ background: "linear-gradient(150deg, #0c2d48 0%, #1565a0 60%, #2e86c1 100%)" }}>
        <div style={{ maxWidth: 700, margin: "0 auto", padding: "20px 16px 24px" }}>
          <Link
            href="/deals"
            style={{
              display: "inline-flex", alignItems: "center", gap: 6,
              fontSize: 13, fontWeight: 600, color: "rgba(255,255,255,0.8)",
              background: "rgba(255,255,255,0.12)", borderRadius: 8,
              padding: "6px 12px", textDecoration: "none", marginBottom: 16,
            }}
          >
            <svg width="16" height="16" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2.5}>
              <path strokeLinecap="round" strokeLinejoin="round" d="M15 19l-7-7 7-7" />
            </svg>
            Dashboard
          </Link>
          <div style={{ display: "flex", alignItems: "center", gap: 14 }}>
            <Image
              src="/logo.png"
              alt="Maxx Orthopedics"
              width={100}
              height={50}
              style={{ height: "auto", filter: "brightness(0) invert(1)", opacity: 0.9 }}
            />
            <div>
              <div style={{ fontSize: 20, fontWeight: 800, color: "#fff", letterSpacing: -0.3 }}>Privacy Policy</div>
              <div style={{ fontSize: 13, color: "rgba(255,255,255,0.65)", marginTop: 2 }}>Maxx HubApp</div>
            </div>
          </div>
        </div>
      </div>

      {/* Content */}
      <div style={{ maxWidth: 700, margin: "0 auto", padding: "24px 16px 48px" }}>

        <div style={{ background: "#fff", borderRadius: 14, border: "1px solid #dce4ec", padding: "28px 24px", marginBottom: 14, boxShadow: "0 1px 3px rgba(0,0,0,0.03)" }}>
          <h2 style={{ fontSize: 16, fontWeight: 700, color: "#0c2d48", marginBottom: 12 }}>Overview</h2>
          <p style={{ fontSize: 14, color: "#374151", lineHeight: 1.7, marginBottom: 0 }}>
            Maxx HubApp is an internal field tool for Maxx Orthopedics sales representatives. It connects to HubSpot CRM to log tasks, add notes, and access deal and contact information from the field. This policy explains how data is handled within the application.
          </p>
        </div>

        <div style={{ background: "#fff", borderRadius: 14, border: "1px solid #dce4ec", padding: "28px 24px", marginBottom: 14, boxShadow: "0 1px 3px rgba(0,0,0,0.03)" }}>
          <h2 style={{ fontSize: 16, fontWeight: 700, color: "#0c2d48", marginBottom: 12 }}>Data We Access</h2>
          <ul style={{ fontSize: 14, color: "#374151", lineHeight: 1.8, paddingLeft: 20, margin: 0 }}>
            <li><strong>HubSpot CRM data</strong> — deals, contacts, tasks, and notes from your organisation's HubSpot account</li>
            <li><strong>NPI Registry</strong> — publicly available provider data from the CMS NPPES registry</li>
            <li><strong>Surgical volume &amp; payment data</strong> — sourced from proprietary databases for competitive intelligence</li>
            <li><strong>AI-generated content</strong> — surgeon profiles generated by Claude AI (Anthropic) using publicly available web information</li>
          </ul>
        </div>

        <div style={{ background: "#fff", borderRadius: 14, border: "1px solid #dce4ec", padding: "28px 24px", marginBottom: 14, boxShadow: "0 1px 3px rgba(0,0,0,0.03)" }}>
          <h2 style={{ fontSize: 16, fontWeight: 700, color: "#0c2d48", marginBottom: 12 }}>How Data Is Used</h2>
          <ul style={{ fontSize: 14, color: "#374151", lineHeight: 1.8, paddingLeft: 20, margin: 0 }}>
            <li>CRM data is used solely to display, create, and update records in your organisation's HubSpot account</li>
            <li>AI-generated surgeon profiles are for informational purposes only and may contain inaccuracies</li>
            <li>No personal data is sold or shared with third parties outside of the services required to operate this application (HubSpot, Anthropic)</li>
            <li>Session data is stored in an encrypted cookie on your device and expires automatically</li>
          </ul>
        </div>

        <div style={{ background: "#fff", borderRadius: 14, border: "1px solid #dce4ec", padding: "28px 24px", marginBottom: 14, boxShadow: "0 1px 3px rgba(0,0,0,0.03)" }}>
          <h2 style={{ fontSize: 16, fontWeight: 700, color: "#0c2d48", marginBottom: 12 }}>Third-Party Services</h2>
          <ul style={{ fontSize: 14, color: "#374151", lineHeight: 1.8, paddingLeft: 20, margin: 0 }}>
            <li><strong>HubSpot</strong> — CRM platform. Data is governed by HubSpot's privacy policy.</li>
            <li><strong>Anthropic (Claude AI)</strong> — AI model provider for task suggestions and surgeon profile generation</li>
            <li><strong>CMS NPPES</strong> — Public federal registry for healthcare providers</li>
          </ul>
        </div>

        <div style={{ background: "#fff", borderRadius: 14, border: "1px solid #dce4ec", padding: "28px 24px", boxShadow: "0 1px 3px rgba(0,0,0,0.03)" }}>
          <h2 style={{ fontSize: 16, fontWeight: 700, color: "#0c2d48", marginBottom: 12 }}>Contact</h2>
          <p style={{ fontSize: 14, color: "#374151", lineHeight: 1.7, margin: 0 }}>
            For questions about this privacy policy or data handling, please contact your Maxx Orthopedics administrator.
          </p>
        </div>

        {/* Footer */}
        <div style={{ marginTop: 32, textAlign: "center" }}>
          <Image
            src="/logo.png"
            alt="Maxx Orthopedics"
            width={100}
            height={50}
            style={{ height: "auto", display: "block", margin: "0 auto 12px", opacity: 0.5 }}
          />
          <p style={{ fontSize: 13, color: "#6b7280", margin: 0 }}>
            <strong style={{ color: "#374151" }}>Maxx HubApp</strong>
          </p>
          <p style={{ fontSize: 12, color: "#94a3b8", marginTop: 4 }}>
            © 2026 Maxx Orthopedics. All rights reserved.
          </p>
          <p style={{ fontSize: 12, marginTop: 8 }}>
            <a href="https://maxxortho.com/privacy-policy/" target="_blank" rel="noopener noreferrer" style={{ color: "#1565a0", textDecoration: "none", fontWeight: 600 }}>
              View full privacy policy at maxxortho.com →
            </a>
          </p>
        </div>
      </div>
    </div>
  );
}
